### ISSUE TITLE
resolve TODO list

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/check#15]
- [x] `panic("invalid URL " + attr) // TODO set error instead of panic`
- [x] `// TODO make thread safe`
- [x] `// TODO it can return error`
- [x] `// TODO return []Page instead []*Page`
- [x] `panic(err) // TODO set error instead of panic`
- [x] `panic("can't find link with URL " + href) // TODO set error instead of panic`
- [x] `panic("can't find page with URL " + href) // TODO set error instead of panic`
- [x] `panic("unexpected URL " + href) // TODO set error instead of panic`

**Comment by kamilsk** [comment]
done
